version: "3"

services:
  fava:
    image: yegle/fava
    container_name: fava
    expose:
      - "5000"
    environment:
      - "VIRTUAL_HOST=fava.zairecloud.pt"
      - "VIRTUAL_PORT=5000"
      - "LETSENCRYPT_HOST=fava.zairecloud.pt"
      - "BEANCOUNT_FILE=/bean/general.beancount"
    volumes:
      - /media/nextcloud/data/nunes/files/Library/Documents/Finance/:/bean
    restart: unless-stopped
    networks:
      - nginx-proxy_network

networks:
  nginx-proxy_network:
    external: true